FROM mcr.microsoft.com/windows/servercore:ltsc2019

ENV MYSQL_ROOT_PASSWORD=k9e234gf1 \
    MYSQL_DATABASE=testdb \
    MYSQL_USER=admin \
    MYSQL_PASSWORD=786fg52ws
	
RUN powershell.exe -Command \
Invoke-WebRequest "https://scriptingteam.s3.us-east-1.amazonaws.com/corentrepo/workloads/windows/Visualstudio/VC_redist_2015_2017_2019.x64.exe" -OutFile C:\windows\Temp\VC_redist_2015_2017_2019.x64.exe; \
Start-Process "C:\windows\Temp\VC_redist_2015_2017_2019.x64.exe" /q; \
sleep 5; \
Invoke-WebRequest "https://scriptingteam.s3.us-east-1.amazonaws.com/corentrepo/workloads/windows/MariaDB/mariadb-10.5.8-winx64.msi" -OutFile C:\mariadb-10.5.8-winx64.msi; \
Remove-Item -Path "C:\windows\Temp\VC_redist_2015_2017_2019.x64.exe" -Force

RUN msiexec /i C:\mariadb-10.5.8-winx64.msi SERVICENAME=MySQL DATADIR=C:\mariadb10.5.8\data PASSWORD=k9e234gf1 PORT=3306 /qn

RUN powershell.exe -Command \
sleep 10; \
Remove-Item -Path "C:\mariadb-10.5.8-winx64.msi" -Force

RUN setx /M PATH "C:\Program Files\MariaDB 10.5\bin;%PATH%;"

EXPOSE 3306

COPY data_privileges.bat /